apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: servidor-python
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: servidor-python
  minReplicas: 5
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
